version: "3.3"

services:
  redis:
    image: redis:3.2.10-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
